name: default

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  integration:
    runs-on: ubuntu-latest

    container: "node:13"

    steps:
      - uses: actions/checkout@v2

      - name: Audit
        run: yarn audit

  delivery:
    runs-on: ubuntu-latest
    needs: integration

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # https://github.com/docker/build-push-action/issues/20
      - name: Get ECR password (tmp)
        run: |
          export ECR_PASSWORD=$(aws ecr get-login-password)
          echo "::set-env name=ECR_PASSWORD::$ECR_PASSWORD"

      - name: Build, tag, and push docker image to AWS ECR
        uses: docker/build-push-action@v1
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          username: AWS  # temporary
          password: ${{ env.ECR_PASSWORD }}  # temporary
          repository: fcd
          tags: ${{ github.sha }},master,latest

      - name: Build, tag, and push docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: terramoney/fcd
          tags: latest
