name: default

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  integration:
    runs-on: ubuntu-latest

    container:
      image: "node:13"

    steps:
      - uses: actions/checkout@v2

      - name: Audit
        run: yarn audit

  delivery:
    runs-on: ubuntu-latest

    needs: integration

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        env:
          REPOSITORY: fcd
        run: |
          docker build -t $REPOSITORY .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag, and push docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_ORG: terramoney
          REPOSITORY: fcd
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag $REPOSITORY $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker tag $REPOSITORY $DOCKER_ORG/$REPOSITORY
          docker push $DOCKER_ORG/$REPOSITORY

      - name: Logout of docker registeries
        if: always()
        run: |
          docker logout ${{ steps.login-ecr.outputs.registry }}
          docker logout
